# tasks/postfix.yml -- Install and configure Postfix
---

- name: Install Postfix
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ mailserver_postfix_packages }}"
  tags:
    - mailserver
    - postfix

- name: Ensure Postfix is started
  service:
    name: "{{ mailserver_postfix_service }}"
    state: started
    enabled: true
  tags:
    - mailserver
    - postfix

- name: Make SSL directory
  file:
    path: /etc/postfix/ssl
    state: directory
    mode: 0755
  tags:
    - mailserver
    - ssl

- name: Copy SSL key to directory
  copy:
    src: files/
    dest: /etc/postfix/ssl
  tags:
    - mailserver
    - ssl

- name: Install postfix main configuration1
  template:
    src: postfix_main.cf.j2
    dest: /etc/postfix/main.cf
  tags: postfix

- name: Install postfix master configuration1
  template:
    src: postfix_master.cf.j2
    dest: /etc/postfix/master.cf
  tags: postfix
  notify: restart postfix
