# tasks/postfix.yml -- Install and configure Postfix
---

- name: Install Postfix
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ mailserver_postfix_packages }}"
  tags:
    - mailserver
    - postfix

- name: Ensure Postfix is started
  service:
    name: "{{ mailserver_postfix_service }}"
    state: started
    enabled: true
  tags:
    - mailserver
    - postfix
